---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-web-active
    image: centos/systemd
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      omero-web-active:
        omero_web_release: latest
scenario:
  name: active
verifier:
  name: testinfra
  lint:
    name: flake8
