---
sudo: required
language: python

services:
  - docker

install:
  # Bug in 2.2.2: https://github.com/ansible/ansible/issues/23016
  - pip install ansible==2.2.1.0 docker 'molecule<1.22'

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
