---
# System dependencies for OMERO.web
# Additional requirements will be installed after OMERO.web has been
# downloaded since it comes with its own requirements.txt
# See web-install.yml

- name: omero web | install python redis package
  become: yes
  yum:
    name: python-redis
    state: present

# selinux

- name: omero web | selinux booleans
  become: yes
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_read_user_content
    - httpd_enable_homedirs
  when: selinux_enabled

# Alternatively set httpd_can_network_connect=yes to allow all ports
- name: omero web | selinux ports
  become: yes
  seport:
    ports: "4080"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled
