---
# Dependencies for OMERO.web

- name: omero web | install python redis package
  become: yes
  yum:
    name: python-redis
    state: present

- name: omero web | setup virtualenv
  become: yes
  pip:
    name:
    - "django>=1.8,<1.9"
    - "django-pipeline>=1.3,<1.4"
    - "django-redis>=4.4"
    - "gunicorn>=19.3"
    - "omero-marshal>=0.5.1,<0.6"
    state: present
    virtualenv: "{{ omero_web_basedir }}/venv"
    virtualenv_site_packages: yes


# selinux

- name: omero web | selinux booleans
  become: yes
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_read_user_content
    - httpd_enable_homedirs
  when: selinux_enabled

# Alternatively set httpd_can_network_connect=yes to allow all ports
- name: omero web | selinux ports
  become: yes
  seport:
    ports: "4080"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled
