---
# selinux

- name: omero web | selinux booleans
  become: true
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  with_items:
    - httpd_read_user_content
    - httpd_enable_homedirs
  when: selinux_enabled

# Alternatively set httpd_can_network_connect=yes to allow all ports
- name: omero web | selinux ports
  become: true
  seport:
    ports: "4080"
    proto: tcp
    setype: http_port_t
    state: present
  when: selinux_enabled
