---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-web-active-py3
    image: centos/systemd
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    # TODO: Can we use the shared playbook in resources?
    converge: playbook.yml
  inventory:
    host_vars:
      omero-web-active-py3:
  options:
    v: true
    diff: true
scenario:
  name: active-py3
  converge_sequence:
    - converge
verifier:
  name: testinfra
  lint:
    name: flake8
