---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-web-active-py3-ubuntu1804
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    # TODO: Install curl in basedeps instead
    prepare: prepare.yml
    # TODO: Can we use the shared playbook in resources?
    converge: ../active-py3/playbook.yml
  inventory:
    host_vars:
      omero-web-active-py3-ubuntu1804:
  options:
    v: true
    diff: true
scenario:
  name: active-py3-ubuntu1804
  converge_sequence:
    - converge
verifier:
  name: testinfra
  # TODO: Use resources or a common folder
  directory: ../active-py3/tests/
  lint:
    name: flake8
