---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-web-py2-py3-upgrade-centos7
    image: centos/systemd
    command: /sbin/init
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../resources/playbook-py2.yml
    converge: ../resources/playbook-py3.yml
  options:
    v: true
    diff: true
scenario:
  name: py2-py3-upgrade-centos7
  converge_sequence:
    - converge
verifier:
  name: testinfra
  directory: ../resources/tests-py3/
  lint:
    name: flake8
